import card from '../../public/images/web-card1.png'; 
import card2 from '../../public/images/web-card2.png'; 
import card3 from '../../public/images/web-card-3.png'; 
import card4 from '../../public/images/web-card4.png'; 
import card5 from '../../public/images/web-card5.png'; 
import card6 from '../../public/images/web-card6.png'; 

export const links = [
    { label: "About Us", url: "/about" },
    { label: "Contact Us", url: "/contact-us" },
    { label: "For Rent", url: "/for-rent" },
    { label: "For Sale", url: "/for-sale" },
    { label: "FAQ", url: "/faq" },
    { label: "Blog", url: "/blog" },
];
export const privacyLinks = [
    { label: "Privacy Policy", url: "/privacy-policy" },
    { label: "Terms and Conditions", url: "/terms-and-condition" },
];

export const propertyCategories = [
        { label: "Flat/Apartment", value: "flat/apartment" },
        { label: "House", value: "house" },
        { label: "Land", value: "land" },
 ];
    
export const propertySize = [
    { label: "1", value: "1" },
    { label: "2", value: "2" },
    { label: "3", value: "3" },
    { label: "4", value: "4" },
    { label: "5", value: "5" },
    { label: "6", value: "6" },
    { label: "6+", value: "6+" },
];


export const propertyPrice = [
    { label: "₦250,000", value: "250,000" },
    { label: "₦500,000", value: "500,000" },
    { label: "₦750,000", value: "750,000" },
    { label: "₦1 Million", value: "1 Million" },
    { label: "₦5 Million", value: "5 Million" },
    { label: "₦10 Million", value: "10 Million" },
    { label: "₦20 Million", value: "20 Million" },
    { label: "₦30 Million", value: "30 Million" },
    { label: "₦40 Million", value: "40 Million" },
    { label: "₦50 Million", value: "50 Million" },
    { label: "₦60 Million", value: "60 Million" },
    { label: "₦70 Million", value: "70 Million" },
    { label: "₦80 Million", value: "80 Million" },
];

export const propertyTypes = [
  { label: "Bungalow", value: "bungalow" },
  { label: "Duplex", value: "duplex" },
  { label: "Terraced House", value: "terraced" },
  { label: "Semi-Detached", value: "semi-detached" },
  { label: "Detached", value: "detached" },
  { label: "Mansion", value: "mansion" },
  { label: "Penthouse", value: "penthouse" },
  { label: "Studio Apartment", value: "studio" },
  { label: "Flat/Apartment", value: "apartment" },
  { label: "Maisonette", value: "maisonette" },
  { label: "Townhouse", value: "townhouse" },
  { label: "Cottage", value: "cottage" },
  { label: "Villa", value: "villa" },
];

export const landTypes = [
  { label: "Residential Land", value: "residential" },
  { label: "Commercial Land", value: "commercial" },
  { label: "Industrial Land", value: "industrial" },
  { label: "Agricultural Land", value: "agricultural" },
  { label: "Mixed-Use Land", value: "mixed-use" },
  { label: "Recreational Land", value: "recreational" },
  { label: "Institutional Land", value: "institutional" },
  { label: "Forestry Land", value: "forestry" },
  { label: "Mining/Extraction Land", value: "mining" },
  { label: "Vacant Land", value: "vacant" },
];

export const nigeriaStates = [
  { label: "Abia", value: "abia" },
  { label: "Adamawa", value: "adamawa" },
  { label: "Akwa Ibom", value: "akwa-ibom" },
  { label: "Anambra", value: "anambra" },
  { label: "Bauchi", value: "bauchi" },
  { label: "Bayelsa", value: "bayelsa" },
  { label: "Benue", value: "benue" },
  { label: "Borno", value: "borno" },
  { label: "Cross River", value: "cross-river" },
  { label: "Delta", value: "delta" },
  { label: "Ebonyi", value: "ebonyi" },
  { label: "Edo", value: "edo" },
  { label: "Ekiti", value: "ekiti" },
  { label: "Enugu", value: "enugu" },
  { label: "Gombe", value: "gombe" },
  { label: "Imo", value: "imo" },
  { label: "Jigawa", value: "jigawa" },
  { label: "Kaduna", value: "kaduna" },
  { label: "Kano", value: "kano" },
  { label: "Katsina", value: "katsina" },
  { label: "Kebbi", value: "kebbi" },
  { label: "Kogi", value: "kogi" },
  { label: "Kwara", value: "kwara" },
  { label: "Lagos", value: "lagos" },
  { label: "Nasarawa", value: "nasarawa" },
  { label: "Niger", value: "niger" },
  { label: "Ogun", value: "ogun" },
  { label: "Ondo", value: "ondo" },
  { label: "Osun", value: "osun" },
  { label: "Oyo", value: "oyo" },
  { label: "Plateau", value: "plateau" },
  { label: "Rivers", value: "rivers" },
  { label: "Sokoto", value: "sokoto" },
  { label: "Taraba", value: "taraba" },
  { label: "Yobe", value: "yobe" },
  { label: "Zamfara", value: "zamfara" },
  { label: "FCT (Abuja)", value: "fct-abuja" },
];

export const propertyListings = [
  {
    label: "4 Bedroom Duplex",
    value: "lekki-phase-1-4bed-duplex",
    beds: 4,
    baths: 4,
    size: "2,500 sqft",
    price: "₦5,000,000",
    location: "Lekki Phase 1, Lagos",
    state: "Lagos",
    status: "open",
    type: "duplex",
    mainImage: card,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
  {
    label: "3 Bedroom Bungalow",
    value: "gwarinpa-3bed-bungalow",
    beds: 3,
    baths: 3,
    size: "1,800 sqft",
    price: "₦3,500,000",
    location: "Gwarinpa, Abuja",
    state: "FCT Abuja",
    status: "open",
    type: "bungalow",
    mainImage: card2,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
  {
    label: "5 Bedroom Mansion",
    value: "asokoro-5bed-mansion",
    beds: 5,
    baths: 6,
    size: "4,500 sqft",
    price: "₦15,000,000",
    location: "Asokoro, Abuja",
    state: "FCT Abuja",
    status: "close",
    type: "mansion",
    mainImage: card,
    images: [
      card,
      card2,
      card4,
      card6,
    ],
  },
  {
    label: "2 Bedroom Flat",
    value: "ikeja-2bed-flat",
    beds: 2,
    baths: 2,
    size: "1,200 sqft",
    price: "₦2,000,000",
    location: "Ikeja, Lagos",
    state: "Lagos",
    status: "open",
    type: "flat",
    mainImage: card3,
    images: [
      card,
      card3,
      card5,
      card4,
    ],
  },
  {
    label: "4 Bedroom Semi-Detached",
    value: "vi-4bed-semi-detached",
    beds: 4,
    baths: 4,
    size: "3,200 sqft",
    price: "₦12,000,000",
    location: "Victoria Island, Lagos",
    state: "Lagos",
    status: "open",
    type: "semi-detached",
    mainImage: card4,
    images: [
      card4,
      card6,
      card2,
      card5,
    ],
  },
  {
    label: "1 Bedroom Studio",
    value: "yaba-1bed-studio",
    beds: 1,
    baths: 1,
    size: "650 sqft",
    price: "₦1,000,000",
    location: "Yaba, Lagos",
    state: "Lagos",
    status: "open",
    type: "studio",
    mainImage: card5,
    images: [
      card5,
      card,
      card4,
      card6,
    ],
  },
  {
    label: "3 Bedroom Terrace",
    value: "lekki-3bed-terrace",
    beds: 3,
    baths: 3,
    size: "2,100 sqft",
    price: "₦6,000,000",
    location: "Lekki, Lagos",
    state: "Lagos",
    status: "close",
    type: "terraced",
    mainImage: card,
    images: [
    card,
    card,
    card,
    card,
    ],
  },
  {
    label: "6 Bedroom Villa",
    value: "maitama-6bed-villa",
    beds: 6,
    baths: 7,
    size: "5,500 sqft",
    price: "₦20,000,000",
    location: "Maitama, Abuja",
    state: "FCT Abuja",
    status: "open",
    type: "villa",
    mainImage: card6,
    images: [
      card6,
      card2,
      card,
      card5,
    ],
  },
  {
    label: "2 Bedroom Apartment",
    value: "wuse2-2bed-apartment",
    beds: 2,
    baths: 2,
    size: "1,400 sqft",
    price: "₦2,800,000",
    location: "Wuse 2, Abuja",
    state: "FCT Abuja",
    status: "open",
    type: "apartment",
    mainImage: card2,
    images: [
      card,
      card3,
      card5,
      card2,
    ],
  },
  {
    label: "3 Bedroom Duplex",
    value: "ph-3bed-duplex",
    beds: 3,
    baths: 3,
    size: "2,000 sqft",
    price: "₦4,000,000",
    location: "Port Harcourt, Rivers",
    state: "Rivers",
    status: "close",
    type: "duplex",
    mainImage: card4,
    images: [
      card2,
      card4,
      card5,
      card6,
    ],
  },
  {
    label: "4 Bedroom Penthouse",
    value: "enugu-4bed-penthouse",
    beds: 4,
    baths: 5,
    size: "3,800 sqft",
    price: "₦8,500,000",
    location: "Independence Layout, Enugu",
    state: "Enugu",
    status: "open",
    type: "penthouse",
    mainImage:card3,
    images: [
      card6,
      card4,
      card3,
      card,
    ],
  },
  {
    label: "3 Bedroom Detached House",
    value: "uyo-3bed-detached",
    beds: 3,
    baths: 3,
    size: "2,400 sqft",
    price: "₦5,500,000",
    location: "Ewet Housing Estate, Uyo",
    state: "Akwa Ibom",
    status: "open",
    type: "detached",
    mainImage: card4,
    images: [
      card2,
      card4,
      card6,
      card,
    ],
  },
  {
    label: "Luxury 5 Bedroom Duplex",
    value: "ikoyi-5bed-duplex",
    beds: 5,
    baths: 6,
    size: "4,800 sqft",
    price: "₦25,000,000",
    location: "Ikoyi, Lagos",
    state: "Lagos",
    status: "close",
    type: "duplex",
    mainImage: card,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
  {
    label: "4 Bedroom Townhouse",
    value: "lekki-4bed-townhouse",
    beds: 4,
    baths: 4,
    size: "3,000 sqft",
    price: "₦9,500,000",
    location: "Lekki, Lagos",
    state: "Lagos",
    status: "open",
    type: "townhouse",
    mainImage: card,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
  {
    label: "2 Bedroom Chalet",
    value: "jos-2bed-chalet",
    beds: 2,
    baths: 2,
    size: "1,300 sqft",
    price: "₦2,200,000",
    location: "Rayfield, Jos",
    state: "Plateau",
    status: "open",
    type: "chalet",
    mainImage: card,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
  {
    label: "3 Bedroom Flat",
    value: "surulere-3bed-flat",
    beds: 3,
    baths: 3,
    size: "1,700 sqft",
    price: "₦3,200,000",
    location: "Surulere, Lagos",
    state: "Lagos",
    status: "close",
    type: "flat",
    mainImage: card,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
  {
    label: "3 Bedroom Apartment",
    value: "aba-3bed-apartment",
    beds: 3,
    baths: 3,
    size: "1,900 sqft",
    price: "₦2,800,000",
    location: "Aba, Abia",
    state: "Abia",
    status: "open",
    type: "apartment",
    mainImage: card,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
  {
    label: "4 Bedroom Duplex",
    value: "kaduna-4bed-duplex",
    beds: 4,
    baths: 4,
    size: "2,800 sqft",
    price: "₦4,500,000",
    location: "Barnawa, Kaduna",
    state: "Kaduna",
    status: "open",
    type: "duplex",
    mainImage: card,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
  {
    label: "2 Bedroom Bungalow",
    value: "owerri-2bed-bungalow",
    beds: 2,
    baths: 2,
    size: "1,600 sqft",
    price: "₦2,000,000",
    location: "Owerri, Imo",
    state: "Imo",
    status: "close",
    type: "bungalow",
    mainImage: card,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
  {
    label: "Luxury 3 Bedroom Villa",
    value: "calabar-3bed-villa",
    beds: 3,
    baths: 4,
    size: "2,700 sqft",
    price: "₦6,500,000",
    location: "Calabar, Cross River",
    state: "Cross River",
    status: "open",
    type: "villa",
    mainImage: card,
    images: [
      card,
      card,
      card,
      card,
    ],
  },
];